sudo: required
dist: trusty

services:
- docker

install:
#- docker-compose pull
#- docker-compose build
- nginx
- gunicorn

script:
- docker build -t database .

deploy:
  - provider: script
    script: bash start-server.sh 
    on:
      branch: ebo
    skip_cleanup: true
