sudo: required
dist: bionic

services:
- docker

install:
#- docker-compose pull
#- docker-compose build
- sudo apt install nginx
- pip install gunicorn

script:
- docker build -t database .

deploy:
  - provider: script
    script: bash deploy.sh 
    on:
      branch: ebo
    skip_cleanup: true
